# angelOS wallpaper / dark
[colors.primary]
background = '#181622'
foreground = '#fafafa'

[colors.cursor]
text = '#181622'
cursor = '#9567b3'

[colors.vi_mode_cursor]
text = '#181622'
cursor = '#b89acc'

[colors.selection]
text = '#181622'
background = '#9567b3'

[colors.search.matches]
foreground = '#181622'
background = '#b89acc'

[colors.search.focused_match]
foreground = '#181622'
background = '#9567b3'

[colors.normal]
black   = '#181622'
red     = '#e36b78'
green   = '#8eaf73'
yellow  = '#d8b56b'
blue    = '#b89acc'
magenta = '#9567b3'
cyan    = '#72b7b0'
white   = '#fafafa'

[colors.bright]
black   = '#b4b5b7'
red     = '#f58b98'
green   = '#aacf93'
yellow  = '#efd18b'
blue    = '#b89acc'
magenta = '#9567b3'
cyan    = '#92d7d0'
white   = '#fafafa'
