# angelOS wallpaper / dark
[colors.primary]
background = '#161722'
foreground = '#fafafa'

[colors.cursor]
text = '#161722'
cursor = '#7a78b3'

[colors.vi_mode_cursor]
text = '#161722'
cursor = '#a7a6cc'

[colors.selection]
text = '#161722'
background = '#7a78b3'

[colors.search.matches]
foreground = '#161722'
background = '#a7a6cc'

[colors.search.focused_match]
foreground = '#161722'
background = '#7a78b3'

[colors.normal]
black   = '#161722'
red     = '#e36b78'
green   = '#8eaf73'
yellow  = '#d8b56b'
blue    = '#a7a6cc'
magenta = '#7a78b3'
cyan    = '#72b7b0'
white   = '#fafafa'

[colors.bright]
black   = '#b4b5b7'
red     = '#f58b98'
green   = '#aacf93'
yellow  = '#efd18b'
blue    = '#a7a6cc'
magenta = '#7a78b3'
cyan    = '#92d7d0'
white   = '#fafafa'
